apiVersion: v1
kind: "Service"
metadata:
  name: as-pushgateway
  namespace: tiflash-autoscale
  labels:
    name: as-pushgateway
spec:
  ports:
  - name: as-pushgateway
    protocol: TCP
    port: 9091
    targetPort: 9091
  selector:
    app: as-pushgateway
  # type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tiflash-autoscale
  labels:
    name: as-pushgateway
  name: as-pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as-pushgateway # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: as-pushgateway
    spec:
      affinity:
        nodeAffinity:  ##serverless speical!!!
          requiredDuringSchedulingIgnoredDuringExecution: ##serverless speical!!!
            nodeSelectorTerms:
            - matchExpressions:
              - key: tiflash.used-for-compute
                operator: NotIn
                values:
                - "true"
      containers:
      - name: pushgateway
        image: prom/pushgateway:v1.4.3
        ports:
        - containerPort: 9091
          protocol: TCP