name: Go Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        golang: [1.19]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.golang }}

      - name: Run tests
        run: make test

